In [8]:
import numpy as np

In [9]:
mylist = [1,2,3]

In [12]:
myarray = np.array(mylist)

In [14]:
myarray

array([1, 2, 3])

In [15]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [16]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.random.rand(5,2)

array([[0.44698236, 0.48356014],
       [0.26848081, 0.77012392],
       [0.3724947 , 0.95236085],
       [0.32583406, 0.17361431],
       [0.91192045, 0.2048146 ]])

In [30]:
np.random.randn(10)

array([-0.71560083, -1.25891975, -0.84304102, -0.2695017 ,  1.18604678,
        0.17401682, -0.08475561,  0.58109195, -0.39783134, -0.22930784])

In [31]:
np.random.randn(2,3)

array([[ 0.32323837,  0.89997086, -0.03786331],
       [ 0.60769498, -0.85608996,  3.16454404]])

In [35]:
np.random.randint(0,101,(4,5))

array([[52, 98, 20, 67, 34],
       [45, 66, 41, 77, 55],
       [48, 64, 23, 92, 68],
       [73, 36, 35, 38,  5]])

In [36]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [37]:
arr = np.arange(0,25)

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranarr = np.random.randint(0,101,10)

In [40]:
ranarr.max()

99

In [42]:
ranarr

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [43]:
ranarr.max()

87

In [44]:
ranarr.argmax()

1

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr.shape

(25,)

In [47]:
arr = arr.reshape(5,5)

In [48]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr.shape

(5, 5)

In [50]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])