In [1]:
import numpy as np

arr =np.arange(0,11)

In [2]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[1:5]

array([1, 2, 3, 4])

In [4]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [5]:
arr[:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [7]:
arr[0:5] = 100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)

In [10]:
slice_of_arr = arr[0:5]

In [11]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [12]:
slice_of_arr[:] = 99

In [13]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [14]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [15]:
arr_copy = arr.copy()

In [16]:
arr_copy[:] = 100

In [17]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [18]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [19]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [20]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
arr_2d.shape

(3, 3)

In [22]:
arr_2d[2]

array([35, 40, 45])

In [23]:
arr_2d[1,1]

25

In [24]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [25]:
arr = np.arange(1,11)

In [26]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [28]:
bool_arr = arr >4

In [29]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [30]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
arr[arr >4]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [33]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [35]:
arr.sum()

55

In [36]:
arr.mean()

5.5

In [37]:
arr.var()

8.25

In [38]:
arr.max()

10

In [39]:
arr.std()

2.8722813232690143

In [40]:
arr_2d = np.arange(0,25).reshape(5,5)

In [41]:
arr_2d.sum()

300

In [42]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [43]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])