In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Advertising.csv')

In [3]:
X = df.drop('sales',axis=1)

In [4]:
y = df['sales']

In [5]:
from sklearn.preprocessing import PolynomialFeatures

In [6]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

In [7]:
poly_features = polynomial_converter.fit_transform(X)

In [8]:
X.shape

(200, 3)

In [9]:
poly_features.shape

(200, 19)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [12]:
X_train.shape

(140, 19)

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
scaler.fit(X_train)

StandardScaler()

In [16]:
X_train = scaler.transform(X_train)

In [17]:
X_test = scaler.transform(X_test)

In [18]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [19]:
#poly_features[0]

In [20]:
from sklearn.linear_model import Ridge

In [21]:
#help(Ridge)

In [22]:
ridge_model = Ridge(alpha=10)

In [23]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [24]:
test_predictions = ridge_model.predict(X_test)

In [25]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [26]:
MAE = mean_absolute_error(y_test,test_predictions)

In [27]:
MAE

0.5774404204714183

In [28]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [29]:
RMSE

0.8946386461319674

In [30]:
from sklearn.linear_model import RidgeCV

In [31]:
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0),scoring='neg_mean_absolute_error')

In [32]:
ridge_cv_model.fit(X_train,y_train)

RidgeCV(scoring='neg_mean_absolute_error')

In [33]:
ridge_cv_model.alpha_

0.1

In [34]:
test_predictions = ridge_cv_model.predict(X_test)

In [35]:
MAE = mean_absolute_error(y_test,test_predictions)

In [36]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [37]:
MAE

0.4273774884342038

In [38]:
RMSE

0.6180719926951576

In [39]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [40]:
#lasso

In [41]:
from sklearn.linear_model import LassoCV

In [42]:
lasso_cv_model = LassoCV(eps=0.1,n_alphas=100,cv=5)

In [43]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [44]:
lasso_cv_model.alpha_

0.4943070909225828

In [45]:
test_predictions = lasso_cv_model.predict(X_test)

In [46]:
MAE = mean_absolute_error(y_test,test_predictions)

In [47]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [48]:
MAE

0.6541723161252856

In [49]:
RMSE

1.130800102276254

In [50]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [51]:
from sklearn.linear_model import ElasticNetCV

In [53]:
elastic_model = ElasticNetCV(l1_ratio=[.1,.5,.7,.9,.95,.99,1],eps=0.001,n_alphas=100,max_iter=1000000)

In [54]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], max_iter=1000000)

In [56]:
elastic_model.l1_ratio_

1.0

In [57]:
elastic_model.alpha_

0.004943070909225827

In [58]:
lasso_cv_model.alpha_

0.4943070909225828

In [59]:
test_predictions= elastic_model.predict(X_test)

In [60]:
MAE = mean_absolute_error(y_test,test_predictions)

In [61]:
RMSE = np.sqrt(mean_squared_error(y_test,test_predictions))

In [62]:
MAE

0.4335034618590066

In [63]:
RMSE

0.6063140748984026